import type { RoastItem } from "@/components/RoastReport";

export interface RoastResult {
  scores: {
    design: number;
    seo: number;
    speed: number;
    conversion: number;
  };
  roastItems: RoastItem[];
  quickWins: string[];
}

const scanMessages = [
  "Fetching DOM structure...",
  "Analyzing page layout...",
  "Checking SEO meta tags...",
  "Evaluating mobile responsiveness...",
  "Measuring visual hierarchy...",
  "Scanning for CTAs...",
  "Calculating performance metrics...",
  "Generating roast report...",
];

export function getScanMessages(): string[] {
  return scanMessages;
}

export function generateMockRoast(url: string): RoastResult {
  // Seed randomness from URL for consistent results per domain
  const hash = url.split("").reduce((a, c) => a + c.charCodeAt(0), 0);
  const rand = (min: number, max: number) => min + ((hash * 13 + min * 7) % (max - min + 1));

  const roastItems: RoastItem[] = [
    {
      title: "Weak Headline",
      problem: "Your headline is as vague as a fortune cookie. It doesn't clearly explain what you offer or who it's for.",
      fix: "Rewrite your headline to clearly explain what you offer and who it's for. Use specific numbers or outcomes.",
    },
    {
      title: "Missing Call-to-Action",
      problem: "No strong CTA above the fold. Visitors have to scroll and hunt to figure out what to do next.",
      fix: "Add a prominent, contrasting CTA button above the fold with action-oriented text like 'Get Started Free'.",
    },
    {
      title: "Poor Mobile Layout",
      problem: "Content overflows on mobile viewports. Text is too small and tap targets are cramped together.",
      fix: "Use responsive breakpoints, increase font size to 16px minimum, and ensure 48px minimum tap target size.",
    },
    {
      title: "Slow Loading Impression",
      problem: "Large unoptimized images and render-blocking scripts create a sluggish first impression.",
      fix: "Compress images to WebP, lazy-load below-fold content, and defer non-critical JavaScript.",
    },
    {
      title: "No Meta Description",
      problem: "Search engines are showing a random snippet from your page because you haven't set a meta description.",
      fix: "Add a compelling meta description under 160 characters that includes your primary keyword.",
    },
    {
      title: "Missing Social Proof",
      problem: "No testimonials, reviews, or trust signals anywhere on the page. New visitors have no reason to trust you.",
      fix: "Add 2-3 customer testimonials with real names and photos near your CTA sections.",
    },
  ];

  const quickWins: string[] = [
    "Add a clear CTA button above the fold with contrasting color",
    "Compress all images and convert to WebP format",
    "Add customer testimonials or social proof near conversion points",
    "Write a specific, benefit-driven headline (not generic)",
    "Include a meta description with your primary keyword",
    "Increase body font size to at least 16px for readability",
    "Add structured data (JSON-LD) for better search appearance",
    "Ensure all links have descriptive anchor text",
  ];

  return {
    scores: {
      design: rand(35, 72),
      seo: rand(28, 65),
      speed: rand(40, 78),
      conversion: rand(22, 58),
    },
    roastItems,
    quickWins,
  };
}

export function generateReportText(url: string, result: RoastResult): string {
  let text = `CARTORY ROASTIFY AI — WEBSITE ROAST REPORT\n`;
  text += `${"=".repeat(50)}\n`;
  text += `URL: ${url}\n`;
  text += `Date: ${new Date().toLocaleDateString()}\n\n`;
  text += `SCORES\n${"-".repeat(30)}\n`;
  text += `Design:     ${result.scores.design}/100\n`;
  text += `SEO:        ${result.scores.seo}/100\n`;
  text += `Speed:      ${result.scores.speed}/100\n`;
  text += `Conversion: ${result.scores.conversion}/100\n\n`;
  text += `ISSUES FOUND\n${"-".repeat(30)}\n`;
  result.roastItems.forEach((item, i) => {
    text += `\n${i + 1}. [${item.title.toUpperCase()}]\n`;
    text += `   Problem: ${item.problem}\n`;
    text += `   Fix: ${item.fix}\n`;
  });
  text += `\nQUICK WINS\n${"-".repeat(30)}\n`;
  result.quickWins.forEach((tip, i) => {
    text += `${i + 1}. ${tip}\n`;
  });
  text += `\n${"=".repeat(50)}\nGenerated by Cartory Roastify AI\n`;
  return text;
}
