project_id = "duozzbamlplvlaecsfos"

[functions.roast-website]
verify_jwt = false

[functions.fix-website]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.brief-prompt]
verify_jwt = false
